import React,{ createContext } from "react";

export const OrchidContext = createContext({
  directory: "",
  setDirectory: () => {},
  themeMode: "light",
  toggleTheme: () => {},
  repoData: null,
  setRepoData: () => {},
  menuOpen: true,
  setMenuOpen: () => {},
  refresh: () => {},
  refreshKey: 0,
  recentDirs: [],
  recentSort: "recent",
  setRecentSort: () => {},
  notRepo: null,
  setNotRepo: () => {},
  removeRecentDir: () => {},
  tabSignal: null,
  setTabSignal: () => {},
  syncWarning: null,
  setSyncWarning: () => {},
  isMerging: false,
  setIsMerging: () => {},
  isReverting: false,
  setIsReverting: () => {},
  rebaseEditRequest: null,
  setRebaseEditRequest: () => {},
  scrollToCommitHash: null,
  setScrollToCommitHash: () => {},
  viewCommit: null,
  setViewCommit: () => {},
  dateFormat: "",
  setDateFormat: () => {},
  isLoading: false,
  setIsLoading: () => {},
});